### ISSUE TITLE
[question] Is there a guide for where to put everything?

### ISSUE THREAD

**Issue by BluGeni** [xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus#2]
For a linuxcnc noob, are there any steps for setting this up? I have the same vfd and am struggling to get it working in linuxcnc. Thanks for any help.

**Comment by xsnoopy** [comment]
Well, I would need a lot more information on where you are standing right now. Basically only thing you need to do is, set the VFD to receive commands over RS485, then download the files and it should work. But it all depends on your current status. E.G. if you are currently using PWM to set the spindle speed, you can remove that from the LinuxCNC hal file.

**Comment by BluGeni** [comment]
I guess I just need to know where to put the files and if there are any other dependencies? I am manually controlling the spindle right now. I do know of a couple config settings I have to set on the vfd to get this working but just need to know where to put and how to reference the files you are talking about.

**Comment by xsnoopy** [comment]
Ok, I'll see that i write something up in the next following days.

**Comment by xsnoopy** [comment]
I added a How To section. Please let me know if that worked.

**Comment by BluGeni** [comment]
Just left for the holidays. I will be able to test this in one week. Can't wait to get this going and I think your notes should get me on the right track. Ill let you know after. Closing for now.
