### ISSUE TITLE
[suggestion] fixing bad response (illegal data value)

### ISSUE THREAD

**Issue by eNnvi** [xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus#3]
Hi there,
I got this VFD partially working via Arduino (i mean that I'm writing an Arduino library to control this VFD) and I got stuck after a while cause I wasn't able to figure out why I was getting bad responses like the ones posted here https://forum.linuxcnc.org/24-hal-components/38733-vfdmod-an-easy-vfd-control-over-modbus-rtu?start=60#218634
Now I see that most people tend to use 9600 baud for serial communication and I thought that going slower was better.
Surprisingly i found that I was wrong! I spent an entire afternoon trying to figure out an algorithm to fix those 0x80 offset in the modbus rtu communication, setting the serial mode to 8E1 (8 bit, 1 stop, even parity), boosting the speed to 38400 baud and setting the inverter address to 10 (0x0A) fixed it.
I should investigate some more (i changed 3 parameters, i should roll back and find which one was actually effective) but right now I'm fine and i hope this could be a fix also for others.

Sorry for the long post but I tried to use as many keywords as possible as you can't find many infos about modbus in this VFD

**Comment by xsnoopy** [comment]
Well, I am not sure how I can help you with this. I just made a few updates to my solution and it seems to work fine. The only problem I have currently is that the VFD read out for Voltage and Current is just garbage.

**Comment by eNnvi** [comment]
That was not an issue but a possible solution (y i know my english is not that great :D ) i just posted it here hoping it could be useful for someone else in the future.

Btw the only issue i'm getting right now is how to decode register values related to VFD error register.
i.e. external error (error code 5 in manual) is reported as error 0x20 in the register and error power off prompt (error code 9 in manual) is reported as error 0x0400.
i believe is a kind of bit setting (like any error is connected to a bit, so u can check multiple errors by checking setted bits in register). This is gonna need some more investigations ('cause i neet to manually trigger all the errors and see the corrisponding register values).
But i'm going OT (i'm writing an Arduino lib, not a linuxcnc "addon"), just sharing what i found hoping it could be useful for others too.
