### ISSUE TITLE
vfd.hal:3: Pin 'vfdmod.spindle.at-speed' does not exist

### ISSUE THREAD

**Issue by Wifiunterputzdose** [xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus#4]
Hi folks,

I did exactly the points which where described in the Howto site but I get everytime the above error message when starting linuxcnc.

I'm using linuxcnc 2.8 also installed vfdmod-0.3.2-stretch-amd64.deb

Can you help me here?

This is how my files looks like:
----------------------------------------------------------------------------------------------------------
My main hal:
VFDMOSTest.hal
https://pastebin.com/y9nGumeW

My main.ini
https://pastebin.com/R7fjCwvb

custom.hal
https://pastebin.com/qgm79xcr

postgui_call_hall.hal
https://pastebin.com/QhxZUZ4F

I put all the vfd.xml stuff into the empty pyvcp-panel.xml
https://pastebin.com/D0u3S7xF

vfd.ini
https://pastebin.com/bg5eSDzJ

vfd.hal
https://pastebin.com/sV2CzPXP

**Comment by xsnoopy** [comment]
Let me check in a bit. Still early in Florida. 

Meanwhile, i would suggest go with my other repository where i did the same thing with classic ladder. It's better and has many advantages.

Grüße nach Deutschland 😁

**Comment by xsnoopy** [comment]
I am running LINUXCNC - 2.8.2-11-g6a3d0a434 your config won't even open in my version of LinuxCNC

**Comment by xsnoopy** [comment]
I guess you need to add this on an empty line for example 231 of your VFDMOSTest.hal 

net spindle-at-speed    => spindle.0.at-speed

**Comment by Wifiunterputzdose** [comment]
Thanks. Meanwhile I tried your other repository and and get it configured. Sadly the converter dont response. Where do you get the setup for the classic ladder?

**Comment by xsnoopy** [comment]
What do you mean? The setup for classic ladder is in the screenshots. The program is available on github. Make sure your vfd has the right address. Is the modus error signal set or unset?

**Comment by Wifiunterputzdose** [comment]
For example I tested this command sequence with a terminal, which works to set the parameter:

Without CRC
[01][06][20][01][01][F4] 

With CRC at the end
[01][06][20][01][01][F4][D3][DD]

[01] is a 8 Byte Hex and so on

How do I implement this in the classic ladder?

**Comment by xsnoopy** [comment]
I would suggest following up here and close this issue. I don't believe it has anything to do with this repository.

https://forum.linuxcnc.org/47-hal-examples/44328-yalang-yl620-vfd-rs485-modbus-communication-vfdmod-or-classicladder

I will follow up with that topic as soon as time allows.
