### ISSUE TITLE
custom.hal execv(vfdmod): No such file or directory

### ISSUE THREAD

**Issue by maxpauley** [xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus#5]
Hello,
Hopefully the images attached okay but i am getting an error upon launch of linuxCNC after following the guide here exactly. I'm not quite sure where I'm going wrong and have tried searching every keyword I could to figure out how to fix this. Any direction or help would be greatly appreciated. I am not experienced with coding nor linuxCNC but am trying to learn. 
Machine information:
PrintNC CNC machine
Yalang Yl620
trying to communicate via rs485
Linuxcnc 2.8

vfd.hal here:
https://pastebin.com/Q2vnxZSX

vfd.ini here:
https://pastebin.com/FmeY3ye3

my machine.hal here:
https://pastebin.com/R07DEF9a

my machine.ini here:
https://pastebin.com/HGmyDzqt

My custom.hal here:
https://pastebin.com/YtMiMPh5

![IMG-9776 (1)](https://user-images.githubusercontent.com/98712009/151716179-bfaeea48-cd9c-4f2c-86aa-e13e2f586fe0.jpg)
![IMG-9777 (1)](https://user-images.githubusercontent.com/98712009/151716182-3c741410-1a45-4320-8dad-1ae9ddc3d065.jpg)
![IMG-9778](https://user-images.githubusercontent.com/98712009/151716185-360b2898-b0b0-4ce8-83d0-ba47158090df.jpg)

**Comment by xsnoopy** [comment]
You need to add the VFD.ini file in the folder .../myfirstcnc/

https://github.com/xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus---VFDmod/blob/main/vfd.ini

**Comment by xsnoopy** [comment]
and make sure you have VFD mod installed https://github.com/aekhv/vfdmod
