### ISSUE TITLE
VFD Errors handling

### ISSUE THREAD

**Issue by driver33** [xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus#6]
Hello. In the first words i want to thank you for very good job. However I have a question about handling errors in the LinuxCNC generated by VFD. I have faced twice at least Error E01 on the VFD  during work and I must press remergency stop manually while it is not handled in LinuxCNC. How it is possible to make soft E-Stop on error from VFD. Do I think correct if 11.0 (status) is for read errors?

**Comment by xsnoopy** [comment]
Yes, I think you are right. I am not sure of VFD Mod can handle that, but classic ladder should be able to do so. Please look at the Classic Ladder integration. https://github.com/xsnoopy/LinuxCNC-Yalang-yl620-VFD-rs485-Modbus-ClassicLadder
